/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PlantInput = IDL.Record({
  'name' : IDL.Text,
  'photo' : ExternalBlob,
});
export const PlantEmotion = IDL.Variant({
  'sad' : IDL.Null,
  'happy' : IDL.Null,
  'angry' : IDL.Null,
  'worried' : IDL.Null,
  'upset' : IDL.Null,
});
export const NeedStatus = IDL.Variant({
  'needsAttention' : IDL.Null,
  'good' : IDL.Null,
});
export const NeedCategory = IDL.Variant({
  'sunlight' : IDL.Null,
  'soil' : IDL.Null,
  'water' : IDL.Null,
  'pestPresence' : IDL.Null,
  'airQuality' : IDL.Null,
});
export const PlantNeed = IDL.Record({
  'status' : NeedStatus,
  'description' : IDL.Text,
  'category' : NeedCategory,
});
export const PlantNeeds = IDL.Vec(PlantNeed);
export const Plant = IDL.Record({
  'id' : IDL.Text,
  'emotion' : PlantEmotion,
  'name' : IDL.Text,
  'needs' : PlantNeeds,
  'photo' : ExternalBlob,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'assessPlant' : IDL.Func([PlantInput], [Plant], []),
  'uploadPhoto' : IDL.Func([ExternalBlob], [ExternalBlob], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PlantInput = IDL.Record({ 'name' : IDL.Text, 'photo' : ExternalBlob });
  const PlantEmotion = IDL.Variant({
    'sad' : IDL.Null,
    'happy' : IDL.Null,
    'angry' : IDL.Null,
    'worried' : IDL.Null,
    'upset' : IDL.Null,
  });
  const NeedStatus = IDL.Variant({
    'needsAttention' : IDL.Null,
    'good' : IDL.Null,
  });
  const NeedCategory = IDL.Variant({
    'sunlight' : IDL.Null,
    'soil' : IDL.Null,
    'water' : IDL.Null,
    'pestPresence' : IDL.Null,
    'airQuality' : IDL.Null,
  });
  const PlantNeed = IDL.Record({
    'status' : NeedStatus,
    'description' : IDL.Text,
    'category' : NeedCategory,
  });
  const PlantNeeds = IDL.Vec(PlantNeed);
  const Plant = IDL.Record({
    'id' : IDL.Text,
    'emotion' : PlantEmotion,
    'name' : IDL.Text,
    'needs' : PlantNeeds,
    'photo' : ExternalBlob,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'assessPlant' : IDL.Func([PlantInput], [Plant], []),
    'uploadPhoto' : IDL.Func([ExternalBlob], [ExternalBlob], []),
  });
};

export const init = ({ IDL }) => { return []; };