/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export type NeedCategory = { 'sunlight' : null } |
  { 'soil' : null } |
  { 'water' : null } |
  { 'pestPresence' : null } |
  { 'airQuality' : null };
export type NeedStatus = { 'needsAttention' : null } |
  { 'good' : null };
export interface Plant {
  'id' : string,
  'emotion' : PlantEmotion,
  'name' : string,
  'needs' : PlantNeeds,
  'photo' : ExternalBlob,
}
export type PlantEmotion = { 'sad' : null } |
  { 'happy' : null } |
  { 'angry' : null } |
  { 'worried' : null } |
  { 'upset' : null };
export interface PlantInput { 'name' : string, 'photo' : ExternalBlob }
export interface PlantNeed {
  'status' : NeedStatus,
  'description' : string,
  'category' : NeedCategory,
}
export type PlantNeeds = Array<PlantNeed>;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'assessPlant' : ActorMethod<[PlantInput], Plant>,
  'uploadPhoto' : ActorMethod<[ExternalBlob], ExternalBlob>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];